### ISSUE TITLE
missing values in mix frequencies data

### ISSUE THREAD

**Issue by AZFARHAD24511** [dhopp1/nowcast_lstm#7]
In the context of LSTM applied to mixed-frequency data, the initial step involves addressing missing data. This is particularly crucial when dealing with a target variable that follows a monthly frequency, while the features are recorded daily. Before any computations take place, it becomes necessary to impute the missing data in the target variable. To illustrate, consider a scenario where, within a one-month timeframe, there exist 29 instances of missing data. My specific inquiry pertains to the underlying logic employed by the LSTM model in handling such a dataset.

**Comment by dhopp1** [comment]
The data/observations the model is being trained on look like this:

y(jan 31st) = (x1(jan 31st) + x1(jan 30th) + ... x1(jan 2nd)) + (x2(jan 31st) + ....)
y(feb 28th) = (x1(feb 28th) + x1(feb 27th) + ... ) + (x2(feb 28th) + ....)
...

So the intervening days, say February 7th, 8th, etc., do not have observations for the target variable and thus are not considered in model training. So no imputation is required. Let me know if this is not clear.

**Comment by AZFARHAD24511** [comment]
> The data/observations the model is being trained on look like this:
> 
> y(jan 31st) = (x1(jan 31st) + x1(jan 30th) + ... x1(jan 2nd)) + (x2(jan 31st) + ....) y(feb 28th) = (x1(feb 28th) + x1(feb 27th) + ... ) + (x2(feb 28th) + ....) ...
> 
> So the intervening days, say February 7th, 8th, etc., do not have observations for the target variable and thus are not observations the model is trained on. So no imputation is required. But of course those daily data are still being considered in the model, since the x1(feb 8th) etc. are inputs for the y(feb28th) target observation.
> 
> Let me know if this is not clear.

The formula you've provided is a pure mathematical expression lacking specific parameters. It only holds true when all the parameters are identical and equal to 1.

**Comment by dhopp1** [comment]
It is a simplified representation to illustrate the structure, not to be taken literally. The point is that the model is only trained on observations where a Y is present, therefore, there is no need to impute intervening Ys.

**Comment by AZFARHAD24511** [comment]
> It is a simplified representation to illustrate the structure, not to be taken literally. The point is that the model is only trained on observations where a Y is present, therefore, there is no need to impute intervening Ys.

Let me put the question this way. Suppose we have several variables (features) that are daily from January 1, 2000 to the end of December 2023 and I have one variable (target variable) that is monthly exactly from January 1, 2000 to the end of December 2023. Now I want to forecast through LSTM for the first two weeks of 2024, while I do not have access to the daily data of the first two weeks of 2024. My specific question is, can I predict the first two weeks of 2024 with my LSTM model? And my second question is, for the target variable which is monthly, can I estimate its daily number from January 1, 2000 to the end of December 2023?
I would be grateful if you could give me a detailed answer.
Thanks

**Comment by Diamong6688** [comment]
RuntimeError                              Traceback (most recent call last)
Cell In[9], line 23
      4 train = test.loc[test.date <= str(pd.to_datetime(date) - pd.tseries.offsets.DateOffset(months=3))[:10],:] # data as it would have appeared at beginning of prediction period
      6 model = LSTM(
      7     data = train,
      8     target_variable = target_variable,
   (...)
     21     optimizer_parameters = {"lr":1e-2, "weight_decay":0.0}
     22 )
---> 23 model.train(quiet=True)
     25 for lag in lags:
     26     # the data available for this date at this artificial vintage
     27     tmp_data = gen_lagged_data(metadata, test, date, lag)

File D:\Anaconda3\envs\Pytorch\lib\site-packages\nowcast_lstm\LSTM.py:144, in LSTM.train(self, num_workers, shuffle, quiet)
    142 optimizer = instantiated["optimizer"]
    143 # train the model
--> 144 trained = self.modelling.train_model(
    145     self.X,
    146     self.y,
    147     mv_lstm,
    148     criterion,
    149     optimizer,
    150     train_episodes=self.train_episodes,
    151     batch_size=self.batch_size,
    152     decay=self.decay,
    153     num_workers=num_workers,
    154     shuffle=shuffle,
    155     quiet=quiet,
    156 )
    157 self.mv_lstm.append(trained["mv_lstm"])
    158 self.train_loss.append(trained["train_loss"])

File D:\Anaconda3\envs\Pytorch\lib\site-packages\nowcast_lstm\modelling.py:139, in train_model(X, y, mv_lstm, criterion, optimizer, train_episodes, batch_size, decay, num_workers, shuffle, quiet)
    136 batch_X, batch_y = batch_X.to(device), batch_y.to(device)
    138 mv_lstm.init_hidden(batch_X.size(0))
--> 139 output = mv_lstm(batch_X)
    140 loss = criterion(output.view(-1), batch_y)
    142 loss.backward()

File D:\Anaconda3\envs\Pytorch\lib\site-packages\torch\nn\modules\module.py:1501, in Module._call_impl(self, *args, **kwargs)
   1496 # If we don't have any hooks, we want to skip the rest of the logic in
   1497 # this function, and just call forward.
   1498 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
   1499         or _global_backward_pre_hooks or _global_backward_hooks
   1500         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1501     return forward_call(*args, **kwargs)
   1502 # Do not call functions when jit is used
   1503 full_backward_hooks, non_full_backward_hooks = [], []

File D:\Anaconda3\envs\Pytorch\lib\site-packages\nowcast_lstm\mv_lstm.py:49, in MV_LSTM.forward(self, x)
     46 batch_size, n_timesteps, _ = x.size()
     48 # model layers
---> 49 x, self.hidden = self.l_lstm(x, self.hidden)
     50 x = x.contiguous().view(batch_size, -1)  # make tensor of right dimensions
     51 x = self.l_linear(x)

File D:\Anaconda3\envs\Pytorch\lib\site-packages\torch\nn\modules\module.py:1501, in Module._call_impl(self, *args, **kwargs)
   1496 # If we don't have any hooks, we want to skip the rest of the logic in
   1497 # this function, and just call forward.
   1498 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
   1499         or _global_backward_pre_hooks or _global_backward_hooks
   1500         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1501     return forward_call(*args, **kwargs)
   1502 # Do not call functions when jit is used
   1503 full_backward_hooks, non_full_backward_hooks = [], []

File D:\Anaconda3\envs\Pytorch\lib\site-packages\torch\nn\modules\rnn.py:812, in LSTM.forward(self, input, hx)
    810 self.check_forward_args(input, hx, batch_sizes)
    811 if batch_sizes is None:
--> 812     result = _VF.lstm(input, hx, self._flat_weights, self.bias, self.num_layers,
    813                       self.dropout, self.training, self.bidirectional, self.batch_first)
    814 else:
    815     result = _VF.lstm(input, batch_sizes, hx, self._flat_weights, self.bias,
    816                       self.num_layers, self.dropout, self.training, self.bidirectional)

RuntimeError: Input and hidden tensors are not at the same device, found input tensor at cuda:0 and hidden tensor at cpu
I made a mistake in the model training times, how should I modify it?

**Comment by dhopp1** [comment]
@Diamong6688 Can you put this in a separate issue? As to not confuse this one. Also there isn't enough information to go off of, you'd have to provide more context, your actual code not just the error message, etc. ` Input and hidden tensors are not at the same device, found input tensor at cuda:0 and hidden tensor at cpu` but this line suggests maybe try not using the GPU and just do everything on the CPU first to make sure it works.

**Comment by diamond-jlu** [comment]
Dear Professor Daniel Hopp, there was an error when I ran your LSTM model. After constant debugging, the model could not be run using only CPU or GPU. Does your code need torch==1.8.1+cpu torchvision==0.9.1+cpu torchaudio===0.8.1 to run? My version of pytorch is 2.0.1. I have created a new question by uploading the wrong code and error according to your requirements, and deleted the original comment. I would be very grateful if you could teach me and solve this problem!


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dhopp1/nowcast_lstm"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月2日(星期六) 晚上6:00
***@***.***&gt;;
抄送:&nbsp;"♔ ***@***.******@***.***&gt;;
主题:&nbsp;Re: [dhopp1/nowcast_lstm] missing values in mix frequencies data (Issue #7)





 
@Diamong6688 Can you put this in a separate issue? As to not confuse this one. Also there isn't enough information to go off of, you'd have to provide more context, your actual code not just the error message, etc.  Input and hidden tensors are not at the same device, found input tensor at cuda:0 and hidden tensor at cpu but this line suggests maybe try not using the GPU and just do everything on the CPU first to make sure it works.

**Comment by dhopp1** [comment]
@AZFARHAD24511 The answer to both your questions is yes. Below is an example that does exactly what you are asking:

```
import numpy as np
import pandas as pd
from nowcast_lstm.LSTM import LSTM

# generating example data
dates = list(pd.date_range("2020-01-01", "2024-01-31",freq = "d")) # data from 2020 to 2024 just for the example to run faster
n_features = 3
data = pd.DataFrame(np.random.rand(len(dates), n_features))
data.columns = ["feature_" + str(i) for i in range(1, n_features+1)]
data["date"] = dates
data = data.loc[:, ["date"] + list(data.columns[:-1])]

target_variable = "feature_3"
data.loc[~data.date.dt.is_month_end, target_variable] = np.nan

# training data up to 2023
train = data.loc[data.date < "2024-01-01", :]

# test data
test = data.copy()
test.loc[data.date >= "2024-01-01", data.columns[1:]] = np.nan # make sure no 2024 data available

# training a model
model = LSTM(
    data = train,
    target_variable = target_variable,
    n_timesteps = 30, # training based on prior 30 days' worth of data
    n_models = 10,
    train_episodes = 50,
    batch_size = int(len(data)/4)
)
model.train()

# if you predict on the test data you can see daily predictions are available
model.predict(test)
```

Keep in mind the example is using random data, so the predictions won't be good, it is just for sake of illustration. Running `model.predict(test)` you can see that now daily predictions are available, including through January 2024. Since this model is trained with a time lag of 30 days, the predictions through January 29th all have some published data to go off of, so vary slightly. For January 30th and 31st, there is no more published data to make predictions off of (they are all NAs), so the model can only predict the mean.

The prediction for January 15th, for example, takes into account data from Decemberr 17th to January 15th. There is data available for December 17th-31st, so that information is used to create the prediction, while the January 1st-15th data, which doesn't exist, goes in as the series mean.

Hopefully this example helps answeer your question.
