### ISSUE TITLE
criterion requirement

### ISSUE THREAD

**Issue by fdfrontdev** [dhopp1/nowcast_lstm#8]
Hi, I need help fixing an error. My target value is either 0 or 1. I already tried scaling my data with MinMaxScaler, but the error persists. 

Thank you in advance.

def lstm_nowcast(train_data,target,new_data):
    from nowcast_lstm.LSTM import LSTM
    import pandas as pd

    train_data['date'] = pd.to_datetime(train_data.index)
    new_data['date'] = pd.to_datetime(new_data.index)
    
    train_data['target'] = target['high_c']
    test_data = pd.concat([train_data, new_data], ignore_index=True)

    import torch.nn as nn

    loss = nn.BCELoss()
    model = LSTM(train_data, "target", n_timesteps=12,n_models=3,train_episodes=20,batch_size=32,criterion=loss)

    model.train()
    result = model.predict(test_data)
    print(result)

error : 
Traceback (most recent call last):
  File "c:/Users/User/Documents/GitHub/test_lstm/main.py", line 175, in <module>
    lstm_nowcast(train_data,target,new_data)
  File "c:/Users/User/Documents/GitHub/test_lstm/main.py", line 91, in lstm_nowcast
    model.train()
  File "C:\Users\User\.conda\envs\practice\lib\site-packages\nowcast_lstm\LSTM.py", line 144, in train
    trained = self.modelling.train_model(
  File "C:\Users\User\.conda\envs\practice\lib\site-packages\nowcast_lstm\modelling.py", line 138, in train_model
    loss = criterion(output.view(-1), batch_y)
  File "C:\Users\User\.conda\envs\practice\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\User\.conda\envs\practice\lib\site-packages\torch\nn\modules\loss.py", line 613, in forward
    return F.binary_cross_entropy(input, target, weight=self.weight, reduction=self.reduction)
  File "C:\Users\User\.conda\envs\practice\lib\site-packages\torch\nn\functional.py", line 2762, in binary_cross_entropy
    return torch._C._nn.binary_cross_entropy(input, target, weight, reduction_enum)
RuntimeError: all elements of input should be between 0 and 1

**Comment by dhopp1** [comment]
The library was made with regression in mind, this is the first time I've seen someone try to use it for binary classification. However I was able to reproduce your error with the following code:

```
from datetime import date, timedelta
import numpy as np
import pandas as pd
from nowcast_lstm.LSTM import LSTM
import torch.nn as nn

n_rows = 20

# making example data
data = pd.DataFrame(np.random.rand(n_rows, 4))
data.columns = ["y", "x1", "x2", "x3"]
data.y = [int(np.round(x)) for x in data.y]
data["date"] = pd.to_datetime([date(2023, 1, 1) + timedelta(days=x) for x in range((timedelta(days = n_rows)).days)])
data = data.loc[:, ["date"] + list(data.columns[:-1])]

# LSTM model
result = None
n_tries = 500
counter = 0
while result is None and counter <= n_tries:
    try:
        counter += 1
        loss = nn.BCELoss()
        model = LSTM(
            data = data, 
            target_variable = "y", 
            n_timesteps = 5,
            n_models = 3,
            train_episodes = 20,
            batch_size = 5,
            criterion = loss
        )
        model.train()
        result = "success"
    except:
         pass
```

The model is actually able to train every once in a while, so if you wrap the model training in a try loop like I did above you will eventually get a correctly trained model. So this is the quick and dirty potential solution to your problem, though this is of course isn't workable for tuning, variable selection, etc.

For the proper diagnosis/fix I will have to dive deeper into the pytorch guts of the modelling and get back to you later.

**Comment by dhopp1** [comment]
OK I figured it out. It will take me a little bit to implement into the library though. As I said the issue was the model was outputting a regression output which could frequently be <0 or >1, which is what then broke the BCELoss() function. To rectify that a sigmoid layer needs to be added to the LSTM to restrict outputs to between 0 and 1. 

You can already use the fix by cloning a local version of the library and making the following addition to [this](https://github.com/dhopp1/nowcast_lstm/blob/main/nowcast_lstm/mv_lstm.py) file:

```
# model layers
x, self.hidden = self.l_lstm(x, self.hidden)
x = x.contiguous().view(batch_size, -1)  # make tensor of right dimensions
x = self.l_linear(x)
x = torch.sigmoid(x) # !!!this is the new line to add
# model layers
```

You're just adding this final `x = torch.sigmoid(x)` layer to the model. If you do this to your local copy and run your code referring to the local library rather than the installed one (I'm not sure of your Python level but let me know if this is not clear) the model will train correctly.

Alternatively you can wait a day or two and I will add this functionality to the published library automatically if the BSELoss() function is passed as the loss function.

**Comment by dhopp1** [comment]
I've added the functionality to [v0.2.6](https://pypi.org/project/nowcast-lstm/0.2.6/). You can update your library and you then should be able to train your model correctly. The library now automatically detects when `BCELoss()` is passed as the criterion and accordingly adds the sigmoid layer.

**Comment by fdfrontdev** [comment]
I tested it and it worked perfectly. Thank you very much
